MD_CAPABILITIES = sorted([
    "SUBSCRIBE",
    "SANE_ORDER_BOOK",
    "PUB_QUOTES",
    "PUB_ORDER_BOOK_POSITIONS",
    "PUB_TRADES",
    "ORDER_BOOK_INCREMENTAL",
])

MD_AVAILABLE_QUOTES = {
    "ask_price": None,
    "ask_size": None,
    "bid_price": None,
    "bid_size": None,
    "close_price": None,
    "daily": {
        "volume": None,
        "high": None,
        "low": None,
        "open": None
    }
}

# Reference:
# https://interactivebrokers.github.io/tws-api/classIBApi_1_1Contract.html#gsc.tab=0

TICKER_FIELDS = [
        {"field": "ib_contract_id",
         "type": "int",
         "label": "IB Contract ID",
         "description": "IB Contract ID identifier"},
        {"field": "symbol",
         "type": "str",
         "label": "Symbol",
         "description": "Symbol of the ticker"},
        {"field": "local_symbol",
         "type": "str",
         "label": "Local Symbol",
         "description": "Local symbol of the ticker in it's primary exchange"},
        {"field": "exchange",
         "type": "str",
         "label": "Exchange",
         "description": "Exchange of the ticker"},
        {"field": "primary_exchange",
         "type": "str",
         "label": "Primary Exchange",
         "description": "Primary exchange of the ticker"},
        {"field": "sec_type",
         "type": "selection",
         "label": "Security Type",
         "description": "Security type of the ticker",
         "content": [
             {"value": "STK",
              "label": "Stock"},
             {"value": "OPT",
              "label": "Option"},
             {"value": "FUT",
              "label": "Future"},
             {"value": "IND",
              "label": "Index"},
             {"value": "FOP",
              "label": "Option on Future"},
             {"value": "CASH",
              "label": "Cash"},
             {"value": "BAG",
              "label": "Combo"},
             {"value": "WAR",
              "label": "Warrant"},
             {"value": "BOND",
              "label": "Bond"},
             {"value": "CMDTY",
              "label": "Commodity"},
             {"value": "FUND",
              "label": "Fund"}]},
        {"field": "expiration",
         "type": "str",
         "label": "Expiration",
         "description": "Last trading day (YYYYMMDD) or "
                        "contract month (YYYYMM) (Options and Futures)"},
        {"field": "strike",
         "type": "float",
         "label": "Strike",
         "description": "Strike price of the ticker (Options)"},
        {"field": "right",
         "type": "selection",
         "label": "Right",
         "description": "Right of the ticker (Options)",
         "content": [
             {"value": "PUT",
              "label": "Put"},
             {"value": "CALL",
              "label": "Call"}]},
        {"field": "multiplier",
         "type": "str",
         "label": "Multiplier",
         "description": "Multiplier of the ticker"},
        {"field": "currency",
         "type": "str",
         "label": "Currency",
         "description": "Currency of the ticker"},
        {"field": "trading_class",
         "type": "str",
         "label": "Trading Class",
         "description": "Trading class of the ticker"},
        {"field": "sec_id_type",
         "type": "str",
         "label": "Security ID Type",
         "description": "Security ID type of the ticker"},
        {"field": "sec_id",
         "type": "str",
         "label": "Security ID",
         "description": "Security ID of the ticker"},
        {"field": "combo_legs_description",
         "type": "str",
         "label": "Combo Legs Description",
         "description": "Description of the combo legs"},
        {"field": "combo_legs",
         "type": "sequence",
         "label": "Combo Legs",
         "description": "List of combo legs",
         "content": [
            {"field": "ib_contract_id",
             "type": "int",
             "label": "IB Contract ID",
             "description": "IB Contract ID identifier"},
            {"field": "exchange",
             "type": "str",
             "label": "Exchange",
             "description": "Exchange of the ticker"},
            {"field": "ratio",
             "type": "int",
             "label": "Ratio",
             "description": "Relative number of contracts for the leg"},
            {"field": "action",
             "type": "selection",
             "label": "Action",
             "description": "The side of the leg",
             "content": ["BUY", "SELL", "SSHORT"]},
            {"field": "open_close",
             "type": "selection",
             "label": "Timing",
             "content": [
                {"value": 0,
                 "label": "Parent"},
                {"value": 1,
                 "label": "Open (Institutional)"},
                {"value": 2,
                 "label": "Close (Institutional)"},
                {"value": 3,
                 "label": "Unknown (Institutional)"}
            ]},
            {"field": "short_sale_slot",
             "type": "selection",
             "label": "Short Sale Slot",
             "description": "Short sale slot for short stock legs",
             "content": [
                 {"value": 1,
                  "label": "Clearing Broker"},
                 {"value": 2,
                  "label": "Third Party"}]},
            {"field": "designated_location",
             "type": "str",
             "label": "Designated Location",
             "description": "Designated location when Short Sale Slot is 2"},
            # add ExemptCode when it's documented by IB?
         ]}
        # Is UnderComp required? What is it?
]
